addEvent('startLiveEvent', true)
addEventHandler('startLiveEvent', resourceRoot, function()
    setFarClipDistance(1700)
    setCloudsEnabled(false)
    testIfGPUIsSupported()
    
    playMusic()
    playMissileAlarm(1)
    setTimer(playMissileAlarm, 8300 / settings.eventSpeed, 1, 2, 1.3)
    setTimer(playMissileAnimation, 11000 / settings.eventSpeed, 1, 1)
    -- playMissileAnimation(3)
end)

addEvent('story:setMissionTarget', true)
addEventHandler('story:setMissionTarget', resourceRoot, function(text)
    exports['m-missions']:setMissionTarget(text)
end)