seasonPass = {
    {
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            stars = 3,
            rarity = 'epic',
            free = true,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {3, 2},
            rarity = 'epic',
            stars = 9,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
        {
            name = 'Testowy skin 2',
            image = '1.png?v4',
            size = {1, 1},
            stars = 3,
            rarity = 'epic',
            free = true,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            rarity = 'epic',
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            stars = 3,
            rarity = 'epic',
            free = true,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {2, 2},
            rarity = 'epic',
            stars = 5,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            rarity = 'epic',
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
    },
    {
        {
            name = 'Testowy skin',
            image = '2.png?v4',
            size = {1, 1},
            stars = 3,
            rarity = 'epic',
            free = true,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {3, 2},
            rarity = 'epic',
            stars = 9,
        },
        {
            name = 'Testowy skin',
            image = '7.png?v4',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
        {
            name = 'Testowy skin',
            image = '4.png?v6',
            size = {1, 1},
            rarity = 'epic',
            free = true,
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '6.png?v4',
            size = {1, 1},
            rarity = 'epic',
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '4.png?v4',
            size = {1, 1},
            rarity = 'epic',
            stars = 3,
        },
        {
            name = 'UFO lampka nocna',
            image = '3.png?v4',
            size = {2, 2},
            rarity = 'epic',
            free = true,
            stars = 5,
        },
        {
            name = 'Testowy skin',
            image = '4.png?v4',
            size = {1, 1},
            rarity = 'epic',
            free = true,
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '5.png?v7',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
        {
            name = 'Testowy skin',
            image = '8.png?v4',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
    },
    {
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            rarity = 'epic',
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {3, 2},
            rarity = 'epic',
            stars = 9,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            rarity = 'epic',
            free = true,
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            rarity = 'epic',
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            rarity = 'epic',
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {2, 2},
            rarity = 'epic',
            stars = 5,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {1, 1},
            rarity = 'epic',
            stars = 3,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
        {
            name = 'Testowy skin',
            image = '1.png?v4',
            size = {2, 1},
            rarity = 'epic',
            stars = 5,
        },
    }
}