furnitures = {
    {
        item = 'toilet1',
        category = 'bathroom',
        name = 'Toaleta',
        description = 'Toaleta w kształcie klasycznej muszli klozetowej',
        icon = 'toilet-1',
        model = 2525,
        rarity = 'common',
        price = 60,
    },
    {
        item = 'toilet2',
        category = 'bathroom',
        name = 'Toaleta',
        description = 'Toaleta w kształcie klasycznej muszli klozetowej',
        icon = 'toilet-2',
        model = 2521,
        rarity = 'uncommon',
        price = 90,
    },
    {
        item = 'toilet3',
        category = 'bathroom',
        name = 'Toaleta',
        description = 'Nowoczesna toaleta',
        icon = 'toilet-3',
        model = 2528,
        rarity = 'rare',
        price = 120,
    },
    {
        item = 'soap1',
        category = 'bathroom',
        name = 'Dyspenser do mydła',
        description = 'Dyspenser do mydła w płynie',
        icon = 'soap-1',
        model = 2741,
        rarity = 'common',
        price = 40,
    },
    {
        item = 'armchair',
        category = 'salon',
        name = 'Klasyczny fotel',
        description = 'Rozsiądź się wygodnie, i pomyśl o swojej przyszłości.\nMożliwość zmiany tekstury.',
        icon = 'armchair1',
        model = 'furniture/KomodaZSzklem',
        rarity = 'common',
        price = 40,
        textures = {'Fotel0', 'Fotel1', 'Fotel2', 'Fotel3'},
    },
    {
        item = 'induction',
        category = 'kitchen',
        name = 'Indukcja',
        description = 'Z naszą indukcją, zrobimy z ciebie najlepszego kucharza.\nMożliwość zmiany tekstury.',
        icon = 'induction1',
        model = 'furniture/Indukcja',
        rarity = 'common',
        price = 40,
        textures = {'plytaindukcja'},
    },
    {
        item = 'toilet',
        category = 'bathroom',
        name = 'Toaleta',
        description = 'Poczuj się jak król, siadając na tym tronie.\nMożliwość zmiany tekstury.',
        icon = 'toilet1',
        model = 'furniture/Kibelek',
        rarity = 'common',
        price = 40,
        textures = {'kibelek'},
    },
    {
        item = 'cabinetWithGlass',
        category = 'salon',
        name = 'Komoda ze szkłem',
        description = 'W nim wszystko jest bezpieczne i stabilne.\nMożliwość zmiany tekstury.',
        icon = 'cabinetwithglass1',
        model = 'furniture/KomodaZSzklem',
        rarity = 'common',
        price = 40,
        textures = {'KomodaZSzklem0', 'KomodaZSzklem1', 'KomodaZSzklem2', 'KomodaZSzklem3'},
    },
    {
        item = 'chair',
        category = 'salon',
        name = 'Krzesło',
        description = 'Proste i wygodne.\nMożliwość zmiany tekstury.',
        icon = 'chair1',
        model = 'furniture/Krzeslo',
        rarity = 'common',
        price = 40,
        textures = {'Krzeslo0', 'Krzeslo1', 'Krzeslo2', 'Krzeslo3'},
    },
    {
        item = 'lamp',
        category = 'salon',
        name = 'Lampa falista',
        description = 'Oświetli rownież twoje serce.\nMożliwość zmiany tekstury.',
        icon = 'lamp1',
        model = 'furniture/Lamp',
        rarity = 'common',
        price = 40,
        textures = {'Lampa0', 'Lampa1'},
    },
    {
        item = 'fridge',
        category = 'kitchen',
        name = 'Lodówka ala aluminium',
        description = 'Możesz się w niej schować podczas wybuchu bomby atomowej.',
        icon = 'fridge1',
        model = 'furniture/Lodowka',
        rarity = 'common',
        price = 40,
        textures = {'lodowka0'},
    },
    {
        item = 'bed',
        category = 'bedroom',
        name = 'Eleganckie łóżko',
        description = 'Nic tylko sie na nie uwalić.\nMożliwość zmiany tekstury.',
        icon = 'bed1',
        model = 'furniture/Lozko',
        rarity = 'common',
        price = 40,
        textures = {'lozko0', 'lozko1', 'lozko2', 'lozko3'},
    },
    {
        item = 'oven',
        category = 'kitchen',
        name = 'Piec elektryczny',
        description = 'Z nim wszystko upieczesz.',
        icon = 'oven1',
        model = 'furniture/Piec',
        rarity = 'common',
        price = 40,
        textures = {'piec'},
    },
    {
        item = 'shower',
        category = 'bathroom',
        name = 'Prysznic',
        description = 'Poczujesz się jak w saunie!\nMożliwość zmiany tekstury.',
        icon = 'shower1',
        model = 'furniture/Prysznic',
        rarity = 'common',
        price = 40,
        textures = {'prysznic1', 'prysznic2'},
    },
    {
        item = 'sofa',
        category = 'salon',
        name = 'Klasyczna kanapa',
        description = 'Rozsiądź się wygodnie, i pomyśl o swojej przyszłości.\nMożliwość zmiany tekstury.',
        icon = 'sofa1',
        model = 'furniture/Sofa',
        rarity = 'common',
        price = 40,
        textures = {'Fotel0', 'Fotel1', 'Fotel2', 'Fotel3'},
    },
    {
        item = 'table',
        category = 'kitchen',
        name = 'Elegancki stół rodzinny',
        description = 'Można na nim robić wszystko.\nMożliwość zmiany tekstury.',
        icon = 'table1',
        model = 'furniture/Stol',
        rarity = 'common',
        price = 40,
        textures = {'Stol0', 'Stol1', 'Stol2', 'Stol3'},
    },
    {
        item = 'chair2',
        category = 'kitchen',
        name = 'Stołek kuchenny',
        description = 'Mały stołek kuchenny.\nMożliwość zmiany tekstury.',
        icon = 'chair2',
        model = 'furniture/Stolek',
        rarity = 'common',
        price = 40,
        textures = {'Stolek0', 'Stolek1', 'Stolek2', 'Stolek3'},
    },
    {
        item = 'coffeeTable',
        category = 'salon',
        name = 'Stolik kawowy',
        description = 'Idealny, żeby oprzeć sobie na nim nogi.\nMożliwość zmiany tekstury.',
        icon = 'coffeetable1',
        model = 'furniture/Stolikkawowy',
        rarity = 'common',
        price = 40,
        textures = {'Stolikkawowy0', 'Stolikkawowy1', 'Stolikkawowy2', 'Stolikkawowy3'},
    },
    {
        item = 'nighttable',
        category = 'bedroom',
        name = 'Stolik nocny',
        description = 'Będzie pasować do każdego łóżka.\nMożliwość zmiany tekstury.',
        icon = 'nighttable1',
        model = 'furniture/SzafkaNocnaMini',
        rarity = 'common',
        price = 40,
        textures = {'SzafkaNocnaMini0', 'SzafkaNocnaMini1', 'SzafkaNocnaMini2', 'SzafkaNocnaMini3'},
    },
    {
        item = 'boxshelf',
        category = 'salon',
        name = 'Szafka pudełkowa',
        description = 'Idealna na różnego rodzaju szpargały.\nMożliwość zmiany tekstury.',
        icon = 'boxshelf1',
        model = 'furniture/SzafkaPudelkowa',
        rarity = 'common',
        price = 40,
        textures = {'SzafkaPudelkowa0', 'SzafkaPudelkowa1', 'SzafkaPudelkowa2', 'SzafkaPudelkowa3'},
    },
    {
        item = 'bath',
        category = 'bathroom',
        name = 'Wanna',
        description = 'Mydło nie jest zawarte w zestawie.',
        icon = 'bath1',
        model = 'furniture/wanna',
        rarity = 'common',
        price = 40,
        textures = {'wanna'},
    },
    {
        item = 'fridgecover',
        category = 'kitchen',
        name = 'Zabudowa lodówki',
        description = 'Otuli twoją lodówkę, kiedy nie będzie cie w domu.\nMożliwość zmiany tekstury.',
        icon = 'fridgecover1',
        model = 'furniture/ZabudowaLodowki',
        rarity = 'common',
        price = 40,
        textures = {'ZabudowaLodowki0', 'ZabudowaLodowki2', 'ZabudowaLodowki3'},
    },
    {
        item = 'sink',
        category = 'bathroom',
        name = 'Zlew kuchenny',
        description = 'Idealny do mycia naczyń i nie tylko.',
        icon = 'sink1',
        model = 'furniture/ZlewKuchnia',
        rarity = 'common',
        price = 40,
        textures = {'zlewkuchnia'},
    },
    {
        item = 'countertop',
        category = 'kitchen',
        name = 'Blat',
        description = 'Blat na szafki i nie tylko.\nMożliwość zmiany tekstury.',
        icon = 'countertop',
        model = 'furniture/Blat',
        rarity = 'common',
        price = 40,
        textures = {'Blat0', 'Blat1', 'Blat2', 'Blat3'},
    },
    {
        item = 'countertopjoin',
        category = 'kitchen',
        name = 'Łączenie blatu',
        description = 'Blat na szafki i nie tylko.\nMożliwość zmiany tekstury.',
        icon = 'countertopjoin1',
        model = 'furniture/BlatLaczenie',
        rarity = 'common',
        price = 40,
        textures = {'Blat0', 'Blat1', 'Blat2', 'Blat3'},
    },
    {
        item = 'countertopleft',
        category = 'kitchen',
        name = 'Koniec blatu (lewy)',
        description = 'Blat na szafki i nie tylko.\nMożliwość zmiany tekstury.',
        icon = 'countertopleft1',
        model = 'furniture/BlatKoniecLewy',
        rarity = 'common',
        price = 40,
        textures = {'Blat0', 'Blat1', 'Blat2', 'Blat3'},
    },
    {
        item = 'countertopright',
        category = 'kitchen',
        name = 'Koniec blatu (prawy)',
        description = 'Blat na szafki i nie tylko.\nMożliwość zmiany tekstury.',
        icon = 'countertopright1',
        model = 'furniture/BlatKoniecPrawy',
        rarity = 'common',
        price = 40,
        textures = {'Blat0', 'Blat1', 'Blat2', 'Blat3'},
    },
    {
        item = 'counterjoin',
        category = 'kitchen',
        name = 'Łączenie szafek',
        description = 'Szafki kuchenne, ale i także do innych pomieszczeń.\nMożliwość zmiany tekstury.',
        icon = 'counterjoin1',
        model = 'furniture/SzafkiLaczenie',
        rarity = 'common',
        price = 40,
        textures = {'Szafki0', 'Szafki1', 'Szafki2', 'Szafki3'},
    },
    {
        item = 'counterdouble',
        category = 'kitchen',
        name = 'Podwójna szafka',
        description = 'Szafki kuchenne, ale i także do innych pomieszczeń.\nMożliwość zmiany tekstury.',
        icon = 'counterdouble1',
        model = 'furniture/SzafkiPodwojna',
        rarity = 'common',
        price = 40,
        textures = {'Szafki0', 'Szafki1', 'Szafki2', 'Szafki3'},
    },
    {
        item = 'countersingle',
        category = 'kitchen',
        name = 'Pojedyńcza szafka',
        description = 'Szafki kuchenne, ale i także do innych pomieszczeń.\nMożliwość zmiany tekstury.',
        icon = 'countersingle1',
        model = 'furniture/SzafkiPojedyncza',
        rarity = 'common',
        price = 40,
        textures = {'Szafki0', 'Szafki1', 'Szafki2', 'Szafki3'},
    },
    {
        item = 'countertablelong',
        category = 'kitchen',
        name = 'Szafka z stołem',
        description = 'Szafka kuchenna z rozuswanym stołem.\nMożliwość zmiany tekstury.',
        icon = 'countertablelong1',
        model = 'furniture/SzafkiRozsuwanyDlugi',
        rarity = 'common',
        price = 40,
        textures = {'Szafki0', 'Szafki1', 'Szafki2', 'Szafki3'},
    },
    {
        item = 'countertableshort',
        category = 'kitchen',
        name = 'Szafka z stolikiem',
        description = 'Szafka kuchenna z rozuswanym stołem.\nMożliwość zmiany tekstury.',
        icon = 'countertableshort1',
        model = 'furniture/SzafkiRozsuwanyKrotki',
        rarity = 'common',
        price = 40,
        textures = {'Szafki0', 'Szafki1', 'Szafki2', 'Szafki3'},
    },
    {
        item = 'uppercabinet',
        category = 'kitchen',
        name = 'Półki ścienne',
        description = 'Idealne na ściane pod trofeum lub do kuchni.\nMożliwość zmiany tekstury.',
        icon = 'uppercabinet1',
        model = 'furniture/PolkiNadBlatem',
        rarity = 'common',
        price = 40,
        textures = {'SzafkiNadBlatem0', 'SzafkiNadBlatem1', 'SzafkiNadBlatem2', 'SzafkiNadBlatem3'},
    },
    {
        item = 'countercabinet2',
        category = 'kitchen',
        name = 'Łączenie szafek ściennych',
        description = 'Pomieszczą każde naczynia.\nMożliwość zmiany tekstury.',
        icon = 'countercabinet2',
        model = 'furniture/SzafkaNadBlatemLaczenie',
        rarity = 'common',
        price = 40,
        textures = {'SzafkiNadBlatem0', 'SzafkiNadBlatem1', 'SzafkiNadBlatem2', 'SzafkiNadBlatem3'},
    },
    {
        item = 'countercabinet3',
        category = 'kitchen',
        name = 'Szafki ścienne',
        description = 'Pomieszczą każde naczynia.\nMożliwość zmiany tekstury.',
        icon = 'countercabinet3',
        model = 'furniture/SzafkiNadBlatem',
        rarity = 'common',
        price = 40,
        textures = {'SzafkiNadBlatem0', 'SzafkiNadBlatem1', 'SzafkiNadBlatem2', 'SzafkiNadBlatem3'},
    },
}

function getFurnitures()
    return furnitures
end

function getFurnitureByModel(model)
    for _, furniture in pairs(furnitures) do
        if furniture.model == model then
            return furniture
        end
    end
end

function getFurniture(item)
    for _, furniture in pairs(furnitures) do
        if furniture.item == item then
            return furniture
        end
    end
end

function getFurnituresByCategory(category)
    local items = {}
    for _, furniture in pairs(furnitures) do
        if furniture.category == category then
            table.insert(items, furniture)
        end
    end
    return items
end